env: "local"
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "social_network"
  sslmode: "disable"  # откл
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
